repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key

  # Block accidental .env commits
  - repo: local
    hooks:
      - id: forbid-env-files
        name: Forbid committing .env* files
        language: system
        entry: bash -c 'echo "Refusing to commit .env* files — add them to .gitignore instead." >&2; exit 1'
        pass_filenames: false
        # Trigger only if any staged file matches these names
        files: '(^|/)\.env(\..+)?$'


  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
