```mermaid
flowchart LR
    id__["NHL-Beyond-27"]
    id_scripts["scripts"]
    id_src["src"]
    id_tests["tests"]
    id__gitignore[".gitignore"]
    id_LICENSE["LICENSE"]
    id_Makefile["Makefile"]
    id_README_md["README.md"]
    id_pyproject_toml["pyproject.toml"]
    id_requirements_txt["requirements.txt"]
    id_tests__gen_arch_diagram_py["gen_arch_diagram.py"]
    id_tests__gen_arch_hr_py["gen_arch_hr.py"]
    id_tests__gen_arch_svg_py["gen_arch_svg.py"]
    id_tests__test_fix_std_one_season_py["test_fix_std_one_season.py"]
    id_scripts__diff_players_normalized_py["diff_players_normalized.py"]
    id_scripts__dump_db_sh["dump_db.sh"]
    id_scripts__gen_mermaid_tree_py["gen_mermaid_tree.py"]
    id_scripts__gen_tree_sh["gen_tree.sh"]
    id_scripts__restore_latest_from_s3_sh["restore_latest_from_s3.sh"]
    id_src__nhl_beyond27["nhl_beyond27"]
    id_src__nhl_beyond27____init___py["__init__.py"]
    id_src__nhl_beyond27__cli_py["cli.py"]
    id_src__nhl_beyond27__pipeline_py["pipeline.py"]
    id__ --> id_scripts
    id__ --> id_src
    id__ --> id_tests
    id__ --> id__gitignore
    id__ --> id_LICENSE
    id__ --> id_Makefile
    id__ --> id_README_md
    id__ --> id_pyproject_toml
    id__ --> id_requirements_txt
    id_tests --> id_tests__gen_arch_diagram_py
    id_tests --> id_tests__gen_arch_hr_py
    id_tests --> id_tests__gen_arch_svg_py
    id_tests --> id_tests__test_fix_std_one_season_py
    id_scripts --> id_scripts__diff_players_normalized_py
    id_scripts --> id_scripts__dump_db_sh
    id_scripts --> id_scripts__gen_mermaid_tree_py
    id_scripts --> id_scripts__gen_tree_sh
    id_scripts --> id_scripts__restore_latest_from_s3_sh
    id_src --> id_src__nhl_beyond27
    id_src__nhl_beyond27 --> id_src__nhl_beyond27____init___py
    id_src__nhl_beyond27 --> id_src__nhl_beyond27__cli_py
    id_src__nhl_beyond27 --> id_src__nhl_beyond27__pipeline_py
```
